name: CI - Automação de Testes Tricentis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restaurar dependências
      run: dotnet restore
      
    - name: Compilar projeto
      run: dotnet build --configuration Release --no-restore
      
    - name: Instalar Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Verificar versão do Chrome
      run: google-chrome --version
      
    - name: Baixar ChromeDriver compatível
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
        echo "Chrome version: $CHROME_VERSION"
        mkdir -p drivers
        wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" -O chrome_version.txt
        CHROMEDRIVER_VERSION=$(cat chrome_version.txt)
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d drivers/
        chmod +x drivers/chromedriver
        
    - name: Executar testes (Modo Headless)
      run: |
        mkdir -p Relatorios
        mkdir -p Evidencias
        dotnet test --configuration Release --no-build --verbosity normal
      env:
        CHROME_HEADLESS: 1
        
    - name: Publicar resultados de teste
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: TestResults/
        
    - name: Publicar relatórios
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: |
          Relatorios/
          Evidencias/
